#!/bin/bash

OUTFILE=index.html

init()
{
    echo "<html>" > ${OUTFILE}
    echo "<head>" >> ${OUTFILE}
    echo "<title>Computational Semantics: First-Order Models of Images</title>" >> ${OUTFILE}
    echo "</head>" >> ${OUTFILE}
    echo "<body>" >> ${OUTFILE}
}

finit()
{
    echo "</body>" >> ${OUTFILE}
    echo "</html>" >> ${OUTFILE}
    chmod 644 ${OUTFILE}

}

wff()
{
    for MODEL in `ls data/*.mod`; do 
	swipl -g "[scripts/wff_model],main('${MODEL}'),halt."
    done
}

html()
{
    SIZE=500
    init
    for IMAGE in `ls data/*0.jpg`; do 
	BASE=`echo ${IMAGE} | cut -d"." -f1`
        cat ${BASE}.mod | tr "\n" "@" | tr -s "@" | tr "@" "\n" | sed 's/, /,/g' > tmp.mod
        mv tmp.mod ${BASE}.mod
	dos2unix -q ${BASE}.mod
	chmod 644 ${BASE}.mod
	chmod 644 ${BASE}.jpg
	if [ -e ${BASE}_bb.jpg ]; then
	    chmod 644 ${BASE}_bb.jpg
	fi
	echo "<table border=\"1\">" >> ${OUTFILE}
        echo "  <tr><th align="left">${BASE}</th><th align="left">model</th></tr>" >> ${OUTFILE}
	if [ -e ${BASE}_bb.jpg ]; then
	    echo "  <tr><td><img src=\"${BASE}_bb.jpg\" alt=\"${IMAGE}\" width=\"${SIZE}\"></img></td>" >> ${OUTFILE}
	else
	    echo "  <tr><td><img src=\"${BASE}.jpg\" alt=\"${IMAGE}\" width=\"${SIZE}\"></img></td>" >> ${OUTFILE}
	fi
        echo "      <td><pre>" >> ${OUTFILE}
	cat ${BASE}.mod >> ${OUTFILE}
        echo "      </pre></td></tr>" >> ${OUTFILE}
        echo "  <tr><td align="right">true:</td><td>" >> ${OUTFILE}
	if [ -e ${BASE}.t ]; then
	    echo "  <p>" >> ${OUTFILE}
	    cat ${BASE}.t >> ${OUTFILE}
	    echo "  </p>" >> ${OUTFILE}
	fi
        echo "  </td></tr>" >> ${OUTFILE}
        echo "  <tr><td align="right">false:</td><td>" >> ${OUTFILE}
	if [ -e ${BASE}.f ]; then
	    echo "  <p>" >> ${OUTFILE}
	    cat ${BASE}.f >> ${OUTFILE}
	    echo "  </p>" >> ${OUTFILE}
	fi
        echo "  </td></tr>" >> ${OUTFILE}
	echo "</table>" >> ${OUTFILE}
	echo "&nbsp;" >> ${OUTFILE}
    done
    finit
}

wff
html

exit 0
